# Generated by Django 5.1.5 on 2025-01-24 04:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('ip_protocol', models.CharField(max_length=128)),
                ('ip_address', models.CharField(max_length=128)),
                ('transport_protocol', models.CharField(max_length=128)),
                ('port', models.CharField(max_length=128)),
                ('network_type', models.CharField(max_length=128)),
                ('peer_id', models.CharField(max_length=128)),
                ('active', models.BooleanField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
